-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 20:35:02 2015
-- Model: Relationships    Version: 2.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema monsterfymvc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `monsterfymvc` ;

-- -----------------------------------------------------
-- Schema monsterfymvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monsterfymvc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `monsterfymvc` ;

-- -----------------------------------------------------
-- Table `monsterfymvc`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`user` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `monsterfymvc`.`user` (`email` ASC);


-- -----------------------------------------------------
-- Table `monsterfymvc`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`module` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `title` VARCHAR(100) NOT NULL DEFAULT 'Módulo',
  `name` VARCHAR(45) NOT NULL DEFAULT 'module',
  `icon` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `monsterfymvc`.`module` (`name` ASC);


-- -----------------------------------------------------
-- Table `monsterfymvc`.`user_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`user_module` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`user_module` (
  `user_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  CONSTRAINT `fk_user_module_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `monsterfymvc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_module_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `monsterfymvc`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_module_user_idx` ON `monsterfymvc`.`user_module` (`user_id` ASC);

CREATE INDEX `fk_user_module_module_idx` ON `monsterfymvc`.`user_module` (`module_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`user` (`id`, `active`, `email`, `password`, `name`) VALUES (1, 1, 'admin@monsterfymvc.com', 'a946ae1df51a10613a6e5624d1daa82c', 'Administrador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`module`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`module` (`id`, `active`, `title`, `name`, `icon`) VALUES (1, 0, 'Dashboard', 'dashboard', DEFAULT);

COMMIT;

