-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 18:47:25 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema incidentmaster
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `incidentmaster` ;

-- -----------------------------------------------------
-- Schema incidentmaster
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `incidentmaster` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `incidentmaster` ;

-- -----------------------------------------------------
-- Table `incidentmaster`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`user` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`client_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`client_type` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`client_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`sales_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`sales_channel` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`sales_channel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`event_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`event_type` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`event_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`product` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`prompter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`prompter` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`prompter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidentmaster`.`calls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incidentmaster`.`calls` ;

CREATE TABLE IF NOT EXISTS `incidentmaster`.`calls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `dt_tm_start` DATETIME NOT NULL,
  `pax_name` VARCHAR(45) NOT NULL,
  `booking` VARCHAR(45) NOT NULL,
  `client_type_id` INT NOT NULL,
  `sales_channel_id` INT NOT NULL,
  `summary` VARCHAR(400) NOT NULL,
  `resolution` VARCHAR(400) NOT NULL,
  `event_type_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `prompter_id` INT NOT NULL,
  `dt_tm_end` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_call_users_idx` (`user_id` ASC),
  INDEX `fk_call_client_type1_idx` (`client_type_id` ASC),
  INDEX `fk_call_sales_channel1_idx` (`sales_channel_id` ASC),
  INDEX `fk_call_event_type1_idx` (`event_type_id` ASC),
  INDEX `fk_call_product1_idx` (`product_id` ASC),
  INDEX `fk_call_prompter1_idx` (`prompter_id` ASC),
  CONSTRAINT `fk_call_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `incidentmaster`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_client_type1`
    FOREIGN KEY (`client_type_id`)
    REFERENCES `incidentmaster`.`client_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_sales_channel1`
    FOREIGN KEY (`sales_channel_id`)
    REFERENCES `incidentmaster`.`sales_channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_event_type1`
    FOREIGN KEY (`event_type_id`)
    REFERENCES `incidentmaster`.`event_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `incidentmaster`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_call_prompter1`
    FOREIGN KEY (`prompter_id`)
    REFERENCES `incidentmaster`.`prompter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `incidentmaster` ;

-- -----------------------------------------------------
-- Placeholder table for view `incidentmaster`.`vw_calls_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidentmaster`.`vw_calls_report` (`Analista` INT, `Atendimento` INT, `PAX` INT, `Reserva` INT, `Tipo de Cliente` INT, `Canal de Vendas` INT, `Resumo` INT, `Solução` INT, `Tipo de Ligação` INT, `Produto` INT, `Causador` INT, `Conclusão` INT);

-- -----------------------------------------------------
-- Placeholder table for view `incidentmaster`.`vw_calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidentmaster`.`vw_calls` (`callId` INT, `userId` INT, `userName` INT, `dtTmStart` INT, `paxName` INT, `booking` INT, `clientTypeId` INT, `clientType` INT, `salesChannelId` INT, `salesChannel` INT, `summary` INT, `resolution` INT, `eventTypeId` INT, `eventType` INT, `productId` INT, `product` INT, `prompterId` INT, `prompter` INT, `dtTmEnd` INT);

-- -----------------------------------------------------
-- View `incidentmaster`.`vw_calls_report`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `incidentmaster`.`vw_calls_report` ;
DROP TABLE IF EXISTS `incidentmaster`.`vw_calls_report`;
USE `incidentmaster`;
CREATE  OR REPLACE VIEW `vw_calls_report` AS
    SELECT 
        `user`.`name` AS `Analista`,
        `calls`.`dt_tm_start` AS `Atendimento`,
        `calls`.`pax_name` AS `PAX`,
        `calls`.`booking` AS `Reserva`,
        `client_type`.`description` AS `Tipo de Cliente`,
        `sales_channel`.`description` AS `Canal de Vendas`,
        `calls`.`summary` AS `Resumo`,
        `calls`.`resolution` AS `Solução`,
        `event_type`.`description` AS `Tipo de Ligação`,
        `product`.`description` AS `Produto`,
        `prompter`.`description` AS `Causador`,
        `calls`.`dt_tm_end` AS `Conclusão`
    FROM
        ((((((`calls`
        JOIN `user` ON ((`calls`.`user_id` = `user`.`id`)))
        JOIN `client_type` ON ((`calls`.`client_type_id` = `client_type`.`id`)))
        JOIN `sales_channel` ON ((`calls`.`sales_channel_id` = `sales_channel`.`id`)))
        JOIN `event_type` ON ((`calls`.`event_type_id` = `event_type`.`id`)))
        JOIN `product` ON ((`calls`.`product_id` = `product`.`id`)))
        JOIN `prompter` ON ((`calls`.`prompter_id` = `prompter`.`id`)))
    ORDER BY `calls`.`dt_tm_start` DESC;

-- -----------------------------------------------------
-- View `incidentmaster`.`vw_calls`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `incidentmaster`.`vw_calls` ;
DROP TABLE IF EXISTS `incidentmaster`.`vw_calls`;
USE `incidentmaster`;
CREATE  OR REPLACE VIEW `vw_calls` AS
    SELECT 
        `calls`.`id` AS `callId`,
        `calls`.`user_id` AS `userId`,
        `user`.`name` AS `userName`,
        `calls`.`dt_tm_start` AS `dtTmStart`,
        `calls`.`pax_name` AS `paxName`,
        `calls`.`booking` AS `booking`,
        `calls`.`client_type_id` AS `clientTypeId`,
        `client_type`.`description` AS `clientType`,
        `calls`.`sales_channel_id` AS `salesChannelId`,
        `sales_channel`.`description` AS `salesChannel`,
        `calls`.`summary` AS `summary`,
        `calls`.`resolution` AS `resolution`,
        `calls`.`event_type_id` AS `eventTypeId`,
        `event_type`.`description` AS `eventType`,
        `calls`.`product_id` AS `productId`,
        `product`.`description` AS `product`,
        `calls`.`prompter_id` AS `prompterId`,
        `prompter`.`description` AS `prompter`,
        `calls`.`dt_tm_end` AS `dtTmEnd`
    FROM
        ((((((`calls`
        JOIN `user` ON ((`calls`.`user_id` = `user`.`id`)))
        JOIN `client_type` ON ((`calls`.`client_type_id` = `client_type`.`id`)))
        JOIN `sales_channel` ON ((`calls`.`sales_channel_id` = `sales_channel`.`id`)))
        JOIN `event_type` ON ((`calls`.`event_type_id` = `event_type`.`id`)))
        JOIN `product` ON ((`calls`.`product_id` = `product`.`id`)))
        JOIN `prompter` ON ((`calls`.`prompter_id` = `prompter`.`id`)))
    ORDER BY `calls`.`dt_tm_start` DESC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `incidentmaster`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (1, 'vinicius.gabriel@tam.com.br', 'Vinicius Gabriel dos Santos', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (2, 'lenyclaudia.oliveira@tam.com.br', 'Lenyclaudia Oliveira', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (3, 'williamc.cabrera@tam.com.br', 'William Cabrera', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (4, 'wendy@tam.com.br', 'Wendy', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (5, 'walter.anjos@tam.com.br', 'Walter Anjos', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (6, 'sabrina.ferreira@tam.com.br', 'Sabrina Ferreira', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (7, 'luciano.sato@tam.com.br', 'Luciano Sato', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (8, 'talita.tenorio@tam.com.br', 'Talita Tenorio', '404f6353b7cfcaed8c809bad91f6c1da');
INSERT INTO `incidentmaster`.`user` (`id`, `email`, `name`, `password`) VALUES (9, 'daniela.sancho@tam.com.br', 'Daniela Sancho', '404f6353b7cfcaed8c809bad91f6c1da');

COMMIT;


-- -----------------------------------------------------
-- Data for table `incidentmaster`.`client_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (1, 'Cliente Direto');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (2, 'Franquia');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (3, 'CVR');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (4, 'Departamento Interno');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (5, 'Fornecedor');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (6, 'Demanda improcedente');
INSERT INTO `incidentmaster`.`client_type` (`id`, `description`) VALUES (7, 'Ligação perdida');

COMMIT;


-- -----------------------------------------------------
-- Data for table `incidentmaster`.`sales_channel`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (1, 'AJUCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (2, 'AUXCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (3, 'BAUCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (4, 'BELCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (5, 'BHZBHS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (6, 'BHZLOU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (7, 'BHZSAV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (8, 'BHZSBV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (9, 'BHZSIP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (10, 'BHZSMI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (11, 'BHZUBE');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (12, 'BJPCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (13, 'BLCCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (14, 'BNUCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (15, 'BPSCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (16, 'BSBASU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (17, 'BSBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (18, 'BVBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (19, 'CACCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (20, 'CAUSNT');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (21, 'CCMSGI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (22, 'CGBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (23, 'CGBSPT');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (24, 'CGRCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (25, 'CGRSBI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (26, 'CPQRCQ');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (27, 'CPQSDP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (28, 'CPQSIG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (29, 'CWBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (30, 'CWBMUE');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (31, 'CWBSCR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (32, 'CWBSEC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (33, 'CWBSPA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (34, 'CWBSPB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (35, 'CWBSSJ');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (36, 'CXJCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (37, 'FLNCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (38, 'FLNXAP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (39, 'FORCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (40, 'FORPAP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (41, 'FORSRO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (42, 'GYNANA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (43, 'GYNCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (44, 'GYNSBV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (45, 'IGUCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (46, 'IMPCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (47, 'ITJRJO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (48, 'JOICTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (49, 'JPACTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (50, 'JPRCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (51, 'LDBAPU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (52, 'LDBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (53, 'LDBGPA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (54, 'MABCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (55, 'MAOCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (56, 'MAOSMA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (57, 'MCPCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (58, 'MCZCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (59, 'MCZSSQ');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (60, 'MEASPM');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (61, 'MGFCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (62, 'MIICTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (63, 'MOGCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (64, 'NATCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (65, 'NATMSS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (66, 'NATSCI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (67, 'PGZSPA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (68, 'PMWPDN');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (69, 'POAPLT');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (70, 'POASBS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (71, 'PPBSPR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (72, 'QDFCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (73, 'QDVCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (74, 'QDVSJU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (75, 'QDVSMX');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (76, 'QGBSPL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (77, 'QHBCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (78, 'QHGRJP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (79, 'QNTCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (80, 'QPECTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (81, 'QSCCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (82, 'QWJRSS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (83, 'RAOCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (84, 'RAOSNR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (85, 'RAOSRP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (86, 'RBRACR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (87, 'RECARS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (88, 'RECCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (89, 'RECJBG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (90, 'RECSRE');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (91, 'RECSTA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (92, 'RIOADR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (93, 'RIOARB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (94, 'RIOCOP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (95, 'RIOCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (96, 'RIOESP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (97, 'RIOIPA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (98, 'RIOSBR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (99, 'RIOSCG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (100, 'RIOSDW');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (101, 'RIOSGA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (102, 'RIOSNA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (103, 'RIOSNT');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (104, 'RIOSRS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (105, 'RIOTJC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (106, 'RVDRNG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (107, 'SAOABC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (108, 'SAOALP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (109, 'SAOAMA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (110, 'SAOARJ');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (111, 'SAOARL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (112, 'SAOARU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (113, 'SAOASL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (114, 'SAOAUG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (115, 'SAOBRB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (116, 'SAOBRK');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (117, 'SAOCTN');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (118, 'SAOELD');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (119, 'SAOHGP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (120, 'SAOIBI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (121, 'SAOIND');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (122, 'SAOITU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (123, 'SAOJFL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (124, 'SAOMKP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (125, 'SAOMOR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (126, 'SAOPZS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (127, 'SAOQCX');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (128, 'SAORAA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (129, 'SAORCC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (130, 'SAORFL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (131, 'SAORMA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (132, 'SAORTS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (133, 'SAOSAF');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (134, 'SAOSAR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (135, 'SAOSBU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (136, 'SAOSCP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (137, 'SAOSFC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (138, 'SAOSGV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (139, 'SAOSIG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (140, 'SAOSIN');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (141, 'SAOSMA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (142, 'SAOSMC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (143, 'SAOSME');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (144, 'SAOSMO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (145, 'SAOSOS');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (146, 'SAOSPE');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (147, 'SAOSRA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (148, 'SAOSSC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (149, 'SAOSTB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (150, 'SAOTAT');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (151, 'SAOVLB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (152, 'SAOWPL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (153, 'SJKCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (154, 'SJPCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (155, 'SJPMRB');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (156, 'SJPSPA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (157, 'SLZCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (158, 'SLZHRP');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (159, 'SLZSIL');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (160, 'SODABV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (161, 'SODCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (162, 'SODSES');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (163, 'SSACTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (164, 'SSAITG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (165, 'SSASCA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (166, 'SSZCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (167, 'SSZSPG');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (168, 'SSZSPI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (169, 'STMSPC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (170, 'THECTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (171, 'UDICTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (172, 'UDIMDC');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (173, 'VDCRCR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (174, 'VIXCTO');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (175, 'VIXLNH');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (176, 'VIXSVI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (177, 'VIXSVI');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (178, 'CVR');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (179, 'SITE TV');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (180, 'MPLU');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (181, 'TLA');
INSERT INTO `incidentmaster`.`sales_channel` (`id`, `description`) VALUES (182, 'DEMANDA IMPROCEDENTE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `incidentmaster`.`event_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (1, 'Não está em viagem ');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (2, 'Ligação perdida ');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (3, 'Alteração serviços ');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (4, 'Demanda improcedente ');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (5, 'Informação ');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (6, 'Elogio');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (7, 'Reclamação | Erro');
INSERT INTO `incidentmaster`.`event_type` (`id`, `description`) VALUES (8, 'Discordância cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `incidentmaster`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (1, 'Discordância cliente');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (2, 'Demanda Improcedente');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (3, 'Sem causador ');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (4, 'Aquisição');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (5, 'Atendimento');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (6, 'Aéreo - Aeroporto / Aeronave');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (7, 'Aéreo - Bagagem');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (8, 'Aéreo - Cancelamento');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (9, 'Aéreo - Cobrança indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (10, 'Aéreo - Emissão');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (11, 'Aéreo - Espaço +');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (12, 'Aéreo - Multa');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (13, 'Aéreo - Nome Errado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (14, 'Aéreo - Pontuação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (15, 'Aéreo - Preço');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (16, 'Aéreo - Reemissão');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (17, 'Aéreo - Schedule');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (18, 'Aéreo - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (19, 'Circuito - Qualidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (20, 'Cruzeiro - Não embarcou');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (21, 'Cruzeiro - Qualidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (22, 'Cruzeiro - Sem reserva');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (23, 'Cruzeiro - Cobrança indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (24, 'Hotel - Cancelamento');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (25, 'Hotel - Check in/out');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (26, 'Hotel - Cobrança indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (27, 'Hotel - Elogio');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (28, 'Hotel - Endereço errado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (29, 'Hotel - Multa');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (30, 'Hotel - Preço');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (31, 'Hotel - Qualidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (32, 'Hotel - Reacomodação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (33, 'Hotel - Sem reserva');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (34, 'Hotel - Solicitação errada');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (35, 'Hotel - Sem pagamento');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (36, 'Hotel - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (37, 'Ingresso - Agendamento');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (38, 'Ingresso - Demora na entrega');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (39, 'Ingresso - Emissão');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (40, 'Ingresso - Usado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (41, 'Locação de veículo - Cobrança indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (42, 'Locação de veículo - Loja fechada');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (43, 'Locação de veículo - Qualidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (44, 'Locação de veículo - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (45, 'Locação de veículo - Sem reserva');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (46, 'Locação de veículo - Sem veículo');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (47, 'Locação de veículo - Solicitação errada');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (48, 'Locação de veículo - Alteração');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (49, 'Mastercard - Disponibilidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (50, 'Mastercard - Preço');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (51, 'Mastercard - Voucher');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (52, 'Pontuação Multiplus TLA - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (53, 'Pontuação Multiplus TLA - Não pontuado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (54, 'Pontuação Multiplus TV - Atraso');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (55, 'Pontuação Multiplus TV - Indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (56, 'Pontuação Multiplus TV - Não pontuado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (57, 'Receptivo - Atraso');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (58, 'Receptivo - Elogio');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (59, 'Receptivo - Qualidade');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (60, 'Receptivo - Sem serviço');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (61, 'Receptivo - Cobrança indevida');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (62, 'Receptivo - Alteração');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (63, 'Receptivo - Alteração');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (64, 'Receptivo - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (65, 'Reembolso - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (66, 'Reembolso - Atraso');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (67, 'Reembolso - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (68, 'Reembolso - Multa');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (69, 'Reembolso - Não solicitado');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (70, 'Reembolso - Tkt Vencido');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (71, 'Site TAM Viagens');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (72, 'Seguro');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (73, 'Trem');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (74, 'TLA - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (75, 'Multiplus - Informação');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (76, 'Documentação de embarque');
INSERT INTO `incidentmaster`.`product` (`id`, `description`) VALUES (77, 'Frete - Cancelamento');

COMMIT;


-- -----------------------------------------------------
-- Data for table `incidentmaster`.`prompter`
-- -----------------------------------------------------
START TRANSACTION;
USE `incidentmaster`;
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (1, 'Não está em viagem ');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (2, 'Ligação perdida ');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (3, 'Alteração serviços ');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (4, 'Demanda improcedente ');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (5, 'Informação ');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (6, 'Elogio');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (7, 'Reclamação | Erro');
INSERT INTO `incidentmaster`.`prompter` (`id`, `description`) VALUES (8, 'Discordância cliente');

COMMIT;

