-- MySQL Script generated by MySQL Workbench
-- Mon Aug  3 00:31:41 2015
-- Model: Relationships    Version: 2.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema monsterfymvc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `monsterfymvc` ;

-- -----------------------------------------------------
-- Schema monsterfymvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monsterfymvc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `monsterfymvc` ;

-- -----------------------------------------------------
-- Table `monsterfymvc`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`user` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `email` VARCHAR(100) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `monsterfymvc`.`user` (`email` ASC);


-- -----------------------------------------------------
-- Table `monsterfymvc`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`module` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`module` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `title` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL DEFAULT 'module',
  `menu_order` INT UNSIGNED NOT NULL,
  `icon` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `monsterfymvc`.`module` (`name` ASC);


-- -----------------------------------------------------
-- Table `monsterfymvc`.`user_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`user_module` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`user_module` (
  `user_id` INT UNSIGNED NOT NULL,
  `module_id` INT UNSIGNED NOT NULL,
  `favorite` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `module_id`),
  CONSTRAINT `fk_user_module_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `monsterfymvc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_module_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `monsterfymvc`.`module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_module_module_idx` ON `monsterfymvc`.`user_module` (`module_id` ASC);

CREATE INDEX `fk_user_module_user_idx` ON `monsterfymvc`.`user_module` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `monsterfymvc`.`tab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `monsterfymvc`.`tab` ;

CREATE TABLE IF NOT EXISTS `monsterfymvc`.`tab` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `module_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `menu_order` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tab_module`
    FOREIGN KEY (`module_id`)
    REFERENCES `monsterfymvc`.`module` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tab_module_idx` ON `monsterfymvc`.`tab` (`module_id` ASC);

USE `monsterfymvc` ;

-- -----------------------------------------------------
-- Placeholder table for view `monsterfymvc`.`vw_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monsterfymvc`.`vw_modules` (`userId` INT, `moduleId` INT, `favorite` INT, `moduleOrder` INT, `moduleActive` INT, `moduleTitle` INT, `moduleName` INT, `moduleIcon` INT, `tabId` INT, `tabOrder` INT, `tabTitle` INT, `tabAction` INT);

-- -----------------------------------------------------
-- View `monsterfymvc`.`vw_modules`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `monsterfymvc`.`vw_modules` ;
DROP TABLE IF EXISTS `monsterfymvc`.`vw_modules`;
USE `monsterfymvc`;
CREATE  OR REPLACE VIEW `vw_modules` AS
	SELECT `user_module`.`user_id` AS `userId`,
		   `module`.`id` AS `moduleId`,
           `user_module`.`favorite`,
           `module`.`menu_order` AS `moduleOrder`,
           `module`.`active` AS `moduleActive`,
           `module`.`title` AS `moduleTitle`,
           `module`.`name` AS `moduleName`,
           `module`.`icon` AS `moduleIcon`,
           `tab`.`id` AS `tabId`,
           `tab`.`menu_order` AS `tabOrder`,
           `tab`.`title` AS `tabTitle`,
           `tab`.`action` AS `tabAction`
	  FROM user_module
      JOIN module ON (`user_module`.`module_id` = `module`.`id`)
      JOIN tab ON (`module`.`id` = `tab`.`module_id`)
  ORDER BY `user_module`.`user_id`,
		       `module`.`menu_order`,
           `tab`.`menu_order`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`user` (`id`, `active`, `email`, `password`, `name`) VALUES (1, 1, 'admin@monsterfymvc.com', 'a946ae1df51a10613a6e5624d1daa82c', 'Administrador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`module`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`module` (`id`, `active`, `title`, `name`, `menu_order`, `icon`) VALUES (1, 1, 'Monsterfy Setup', 'system', 2, ' ');
INSERT INTO `monsterfymvc`.`module` (`id`, `active`, `title`, `name`, `menu_order`, `icon`) VALUES (2, 1, 'Dashboard', 'dashboard', 1, ' ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`user_module`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`user_module` (`user_id`, `module_id`, `favorite`) VALUES (1, 1, 0);
INSERT INTO `monsterfymvc`.`user_module` (`user_id`, `module_id`, `favorite`) VALUES (1, 2, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `monsterfymvc`.`tab`
-- -----------------------------------------------------
START TRANSACTION;
USE `monsterfymvc`;
INSERT INTO `monsterfymvc`.`tab` (`id`, `active`, `module_id`, `title`, `action`, `menu_order`) VALUES (1, 1, 1, 'Usuários', 'listUsers', 1);
INSERT INTO `monsterfymvc`.`tab` (`id`, `active`, `module_id`, `title`, `action`, `menu_order`) VALUES (2, 1, 1, 'Módulos', 'listModules', 2);

COMMIT;

